def scmVars

pipeline {
    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '5', artifactNumToKeepStr: '5', daysToKeepStr: '5', numToKeepStr: '5')
        timeout(15)
    }
    agent any
    environment {
        MAVEN_ADDITIONAL_TARGETS = "${mavenAdditionalTargets}"
    }
    stages {
        stage('Test') {
            steps {
                sh 'env'
            }
        }
        stage('Checkout') {
            steps {
                script {
                    scmVars = checkout scm
                }
                echo "scmVars=${scmVars}"
            }
        }
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn clean verify -C -e --show-version'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
